function desc = autoGenerateDescription(params)
    desc = "";
    flds = fieldnames(params);
    for i = 1:length(flds)
        v = params.(flds{i});
        if length(v) > 1
            desc = desc + sprintf('%s=[%s]; ', flds{i}, join(string(v), ', '));
        end
    end
end