function desc = autoGenerateDescription(params)%run this to check
    desc = "iterating through";
    flds = fieldnames(params);
    for i = 1:length(flds)
        v = unique(params.(flds{i}));
        if length(v) > 1
            desc = desc + sprintf('%s=[%s]; ', flds{i}, join(string(v), ', '));
        end
    end
end
