function name = getDisplayName(param)
    names = struct( ...
        'fiberRadius', 'Radius of Fiber (/μm)', ...
        'xLen', 'Length of Fiber (/μm)', ...
        'ledDistance', 'LED Distance from Fiber (mm)', ...
        'nFiber', 'Imaginary Refractive Index', ...
        'nMetal', 'Metal Refractive Index', ...
        'ray_sqrt', 'Ray Fidelity Number', ...
        'scatterNumber', 'Scatter Fidelity Number', ...
        'dxNum', 'dx Fidelity (μm)', ...
        'intensityMin', 'Minimum Intensity Tracked (μW/cm²)', ...
        'smaNum', 'Number of Housing Bounces', ...
        'maxScatterAngle', 'Max Scatter Angle (rad)', ...
        'maxBounce', 'Max Fiber Bounces', ...
        'rayScatterCoeff', 'Rayleigh Scattering Portion', ...
        'smaFillLength', 'SMA Fill Length (μm)', ...
        'waterStatus', 'Water Medium (Boolean)');
    name = names.(param);
end
